# Linear Algebra Review

## Matriks dan Vektor



In [24]:
import numpy as np



In [25]:
matrix_a = np.matrix('1 2 3; 4 5 6;7 8 9;10 11 12')
print(matrix_a)

vector_v=np.array([1,2,3])
print(vector_v)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]


Get the dimension of the matrix A (m,n) where m = rows and n = columns

In [26]:
matrix_a.shape

(4, 3)

## Addition and Scalar Multiplication

In [30]:
# Initialize matrix A and B 
matrix_a = np.matrix('1, 2, 4; 5, 3, 2')
matrix_b = np.matrix('1, 3, 4; 1, 1, 1')
c = 2

print(matrix_a)
print(matrix_b)



[[1 2 4]
 [5 3 2]]
[[1 3 4]
 [1 1 1]]


See how element-wise addition works


In [31]:
add_ab = matrix_a + matrix_b
print(add_ab)

[[2 5 8]
 [6 4 3]]


See how element-wise subtraction works

In [33]:
sub_AB = matrix_a - matrix_b
print(sub_AB)

[[ 0 -1  0]
 [ 4  2  1]]


See how scalar multiplication works

In [35]:
mult_scalar_a = matrix_a * c;
print(mult_scalar_a)

[[ 2  4  8]
 [10  6  4]]


Divide A by s

In [37]:
div_scalar_a = matrix_a / c
print(div_scalar_a)


[[0.5 1.  2. ]
 [2.5 1.5 1. ]]


What happens if we have a Matrix + scalar?

In [38]:
add_scalar_a = matrix_a + c
print(add_scalar_a)


[[3 4 6]
 [7 5 4]]


## Matrix Vector Multiplication